# Generated by Django 5.0.6 on 2024-07-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='third_party_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='slug',
            field=models.SlugField(default=True, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
