# Generated by Django 5.0.6 on 2024-07-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_site', '0002_game_third_party_id_reviews_slug_reviews_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
