# Generated by Django 5.0.6 on 2024-07-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_site', '0003_alter_reviews_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='third_party_id',
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='min_players',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='playing_time',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
