# Generated by Django 5.0.6 on 2024-07-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_site', '0005_rename_reviews_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='player_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_played',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='game_duration',
            field=models.PositiveIntegerField(help_text='Game time in minutes', null=True),
        ),
    ]
