# Generated by Django 5.0.6 on 2024-07-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_site', '0006_review_player_count_alter_review_date_played_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='local_image_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
