# Generated by Django 5.0.6 on 2024-07-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_site', '0007_game_local_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='local_image_path',
        ),
        migrations.AlterField(
            model_name='review',
            name='date_played',
            field=models.DateField(null=True),
        ),
    ]
