# Generated by Django 5.0.6 on 2024-07-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_site', '0008_remove_game_local_image_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_played',
            field=models.DateField(help_text='MM/DD/YYY', null=True),
        ),
    ]
